spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_guinness
    username: postgres
    password: postgres

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
