spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_guinness
    username: campus
    password: campus

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
